domain: "poisson.development.run"
# Helm does not recommend using floating image tags like latest, head etc.
# It is recommended to use a fixed tag.
ravenImageTag: latest
packageFilePath: misc/pack.zip
storageSize: 5Gi
ingressClassName: nginx

imagePullPolicy: IfNotPresent

# RavenDB nodes
# todo: allow to define more than 3 nodes with custom tags etc.
nodes:
  - nodeTag: "A"
    publicTcpPort: 38887
  - nodeTag: "B"
    publicTcpPort: 38888
  - nodeTag: "C"
    publicTcpPort: 38889
environment:
  MY_ENV: 'amongus'
