{{ if eq .Values.ingressClassName "nginx" }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: tcp-services
  namespace: ingress-nginx
data:
  {{- range .Values.nodes }}
  {{.publicTcpPort}}: "ravendb/ravendb-{{.nodeTag | lower }}:38888"
  {{- end }}
{{ end }} 