apiVersion: v1
entries:
  ravendb-cluster:
  - apiVersion: v1
    appVersion: "5.3"
    created: "2022-10-14T10:18:40.6356697+02:00"
    description: Chart for RavenDB Cluster
    digest: cc9e06a1f554a821420d59228e2e386c7e9eeb336dc2230aad5b095de8f3e0b1
    icon: https://ravendb.net/img/repository-icon.svg
    name: ravendb-cluster
    urls:
    - ravendb-cluster/package/ravendb-cluster-2.0.1.tgz
    version: 2.0.1
generated: "2022-10-14T10:18:40.6346695+02:00"
