apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: modify-config
  namespace: ravendb
  labels:
    app.kubernetes.io/name: ravendb
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"

subjects:
  - kind: ServiceAccount
    name: modify-config
    namespace: ravendb
roleRef:
  kind: Role
  name: modify-config
  apiGroup: rbac.authorization.k8s.io
