apiVersion: v1
kind: Secret
metadata:
  namespace: ravendb
  name: ravendb-setup-package
  labels:
    app.kubernetes.io/name: ravendb
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
type: Opaque
data:
{{ (.Files.Glob .Values.packageFileGlobPath).AsSecrets | indent 2 }}
