apiVersion: v1
kind: Secret
metadata:
  namespace: ravendb
  name: ravendb-certs
  labels:
    app.kubernetes.io/name: ravendb
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
type: Opaque
data:
  {{- range .Values.nodeTags }}
  {{ . | lower}}.pfx: {{ "no-cert" | b64enc}}
  {{- end }}
