kind: ConfigMap
apiVersion: v1
metadata:
  name: ravendb-scripts
  namespace: ravendb
  labels:
    app.kubernetes.io/name: ravendb
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
data:
{{ (.Files.Glob "scripts/create-cluster.sh").AsConfig | indent 2 }}
{{ (.Files.Glob "scripts/get-server-cert.sh").AsConfig | indent 2 }}
{{ (.Files.Glob "scripts/update-cert.sh").AsConfig | indent 2 }}
{{ (.Files.Glob "scripts/initialize-pod.sh").AsConfig | indent 2 }}
  domain: {{.Values.domain}}
