{{- range .Values.nodes }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "ravendb-{{.nodeTag | lower }}"
  namespace: ravendb
  annotations: 
    ingress.kubernetes.io/ssl-passthrough: "true"
  labels:
    app.kubernetes.io/name: ravendb
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    helm.sh/chart: "{{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}"
    nodeTag: "{{.nodeTag}}"
spec:
  selector:
    matchLabels:
      nodeTag: "{{.nodeTag}}"
  serviceName: "ravendb-{{.nodeTag | lower }}"
  replicas: 1
  template:
    metadata:
      namespace: ravendb
      labels:
        nodeTag: "{{.nodeTag}}"
    spec:
      dnsPolicy: Default
      serviceAccountName: modify-config
    
      initContainers:
      - name: "{{$.Chart.Name}}-init"
        # todo: use lighter distro to run the scripts
        image: "ubuntu:latest"  
        command: ["/bin/bash"]
        args: ["/ravendb/scripts/initialize-pod.sh"]

        volumeMounts:
          - name: ravendb-scripts
            mountPath: /ravendb/scripts
          - name: ravendb-setup-package
            mountPath: /usr/ravendb
          - name: ravendb-certs
            mountPath: /ravendb/certs
          - name: ravendb-env
            mountPath: /ravendb/env
            readOnly: false

      containers:
      - name: ravendb-container
        image: "ravendb/ravendb:{{$.Values.ravenImageTag}}"
        imagePullPolicy: {{ $.Values.imagePullPolicy }}
        ports:
        - containerPort: 443
          name: https
        - containerPort: 38888
          name: tcp
          protocol: TCP

        env:
        - name: RAVEN_Setup_Mode
          valueFrom:
            configMapKeyRef:
              name: ravendb-env
              key: raven_setup_mode
        - name: RAVEN_Security_Certificate_LetsEncrypt_Email
          valueFrom:
            configMapKeyRef:
              name: ravendb-env
              key: raven_security_certificate_letsencrypt_email

        - name: RAVEN_License
          valueFrom:
            configMapKeyRef:
              name: ravendb-env
              key: raven_license

        - name: RAVEN_License_Eula_Accepted
          value: 'true'
        - name: RAVEN_ServerUrl
          value: "https://0.0.0.0:443"
        - name: RAVEN_ServerUrl_Tcp
          value: "tcp://0.0.0.0:38888"

        - name: RAVEN_ARGS
          value: --Security.Certificate.Load.Exec=/ravendb/scripts/get-server-cert.sh --Security.Certificate.Exec.TimeoutInSec=60 --Security.Certificate.Change.Exec=/ravendb/scripts/update-cert.sh

        - name: RAVEN_PublicServerUrl
          value: "https://{{ .nodeTag | lower }}.{{$.Values.domain}}:443"
        - name: RAVEN_PublicServerUrl_Tcp
          value: "tcp://{{ .nodeTag | lower }}-tcp.{{$.Values.domain}}:{{.publicTcpPort}}"

        # The environmental values defined in the values.yaml should be listed below this comment while debugging
        {{ if ( $.Values.environment )}}
        {{- range $key, $val := $.Values.environment }}
        - name: {{ $key }}
          value: {{ $val }}
        {{ end -}}
        {{ end }}

        volumeMounts:
          - name: ravendb-scripts
            mountPath: /ravendb/scripts
          - name: ravendb-setup-package
            mountPath: /usr/ravendb
          - name: ravendb-certs
            mountPath: /ravendb/certs
          - name: "ravendb"
            mountPath: /opt/RavenDB/Server/RavenData
          - name: ravendb-env
            mountPath: /ravendb/env

      volumes:
        - name: ravendb-scripts
          configMap:
            name: ravendb-scripts
            defaultMode: 0700
        - name: ravendb-env
          configMap:
            name: ravendb-env
            defaultMode: 0700
        - name: ravendb-certs
          secret:
            secretName: ravendb-certs
        - name: ravendb-setup-package
          secret:
            secretName: ravendb-setup-package

  volumeClaimTemplates:
    - metadata:
        name: ravendb
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ $.Values.storageSize }}
---
{{- end }}
